apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mrot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mrot
    app.kubernetes.io/part-of: cin4s-839-0002-app
  name: devfile-sample-mrot
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mrot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mrot
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0002-tenant/cin4s-839-0002-app/devfile-sample-mrot@sha256:099e825e3633c44147aa4dc88e00b6a0aa6b76be1038f98949e8da45ecf60625
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
